version: '2'
services:
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse-web:
    image: gregoryarcara/concourse-bin
    command: /root/scripts/start.sh web
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_LOGIN: 'myuser'
      CONCOURSE_PASSWORD: 'mypass'
      CONCOURSE_EXTERNAL_URL: 'http://0.0.0.0:8080/'
    links:
      - concourse-db

  concourse-worker:
    image: gregoryarcara/concourse-bin
    privileged: true
    command: /root/scripts/start.sh worker
    links:
      - concourse-web
      - concourse-db
